Edit docs - Add section with example of getting a user's inventory
joalla/discogs_client pull request #123
Opened 2023-01-17 19:18 UTC by lemonase

## Problem

In regards to **Marketplace Listings** - there are examples for Create, Update and Delete but not Read.

I will admit that this is something that confused me at first, so I wanted to add examples for others who maybe trying to do the same.

## Pull Request

Pull request to update the README and docs with examples of how you can read and get listings from a user's inventory without authenticating as said user.

2023-01-18 12:06 UTC, JOJ0 commented
As a first time contributor I had to approve or gh actions workflows to run. I did that just now.

What you could also do to make sure the docs looks as i tended: Build them locally. See docs page: https://python3-discogs-client.readthedocs.io/en/latest/writing_docs.html

The note about Py 3.10 issues might be outdated. Please report if your build went fine and I'll update this part of the docs.

2023-01-18 17:51 UTC, lemonase commented
Yes, thank you. The angle brackets around the links are from my editor doing autoformatting. It doesn't effect the rendering/output of the markdown on GitHub or the docs so either way works.

I was able to build the sphinx docs using Python 3.9.6 and 3.10.6 as well.

2023-01-19 08:11 UTC, JOJ0 requested changes
Regarding the < and > bracket characters: Can you provide information and documentation describing that this is proper markdown syntax? On a quick search I didn't find much. At least the discogs documentation suggests writing links without them: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links. I suggest we leave it as it is as long as we don't have a good reason to change them.

2023-01-19 08:11 UTC, JOJ0 commented on README.mkd
> +
I'm just not sure if I like our mixture of REPL and regular code on the README page. This is certainly not your fault but our own. It's not too much of a big deal but still everything in one style would probably cleaner.

Since everything else is in REPL style on this page I think your addition is fine as it is. If you feel motivated though you could include changing the existing marketplace-add-listing-code to REPL style. If not, that's perfectly fine, really! :-)

2023-01-19 08:11 UTC, JOJ0 commented on docs/source/listing.md
> +````
Please add the final step of accessing a release as you did on the README version of this code. I think it adds to clarity if people read through the docs without having exactly read the README in detail before!

2023-01-20 04:19 UTC, lemonase commented
> Regarding the < and > bracket characters: Can you provide information and documentation describing that this is proper markdown syntax? On a quick search I didn't find much. At least the discogs documentation suggests writing links without them: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links. I suggest we leave them as they are as long as we don't have a good reason to change them.

The only thing I can refer you to for this is the VS Code extension I had installed [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)
The extension is simply more opinionated/aggressive with formatting than others.

I can certainly revert these - as I didn't necessarily intend to make these changes in the first place.

Everything else concerning styling/consistency is fine as well.

2023-01-20 04:27 UTC, lemonase commented on README.mkd
> +
This may be just me, but I didn't even notice the difference between a REPL and regular code.
This is probably because the code examples are so short... longer blocks with functions and classes would be a different story.

Code examples in official python docs are REPL style for example.
https://docs.python.org/3/library/datetime.html

2023-01-20 13:47 UTC, JOJ0 commented
Thanks for the changes. I'd prefer the links to revert without those brackets. Quickly looked throught that linters specs but couldnt find anything, but was on mobile and not thorough: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md042---no-empty-links

In any case: Consistency throughout the docs is good, so better we leave them.

2023-01-20 13:50 UTC, JOJ0 commented
Guys @alifhughes @prcutler @AnssiAhola anything from your end when you look at the final diff or we ready to merge?

2023-01-20 14:18 UTC, AnssiAhola commented
Overall it looks fine to me, maybe the "unnecessary" code formatting (white space, links, etc) throws me off a bit, but I think it's fine as is.

About those links being converted by the linter, maybe it's triggered by [this rule](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md034---bare-url-used) and it thinks that `(` and `)` around links are considered "bare url"?
Although [this rule](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md011---reversed-link-syntax) indicates that the original syntax was correct. hmm... a bug?  :thinking:

Anyway maybe we should make a separate PR where we go through the docs and make them consistent and "correct"? Maybe using this linter or a non-buggy one :sweat_smile:

2023-01-20 15:44 UTC, JOJ0 commented
Thanks for the review @AnssiAhola and nice catch: Could really be a bug in that linter with the bare-url.

So, to conclude all this please @lemonase remove the < > brackets from links and leave the empty lines between the chapters.

Thanks again!

2023-01-20 19:26 UTC, lemonase commented
Thanks you guys, I've reverted any type of formatting and just left the code examples.

But I did figure out the reason for the angle brackets...
All the links in README.mkd begin on newlines, which makes markdownlint think they are bare links.
When the text and link are on the same line, no angle brackets.

2023-01-20 19:29 UTC, lemonase commented on README.mkd
> -<https://python3-discogs-client.readthedocs.org>),
markdownlint thought this was a "bare link", hence angle brackets.

2023-01-21 13:38 UTC, prcutler commented
Sorry for the delay - LGTM!  And thanks for the PR!

2023-01-21 17:34 UTC, JOJ0 commented
anyone give me a approve button push. thanks :-)

2023-01-21 17:48 UTC, AnssiAhola approved these changes
LGTM!

2023-01-22 04:01 UTC, lemonase reviewed
Comment for final review

2023-01-22 12:49 UTC, JOJ0 approved these changes
LGTM, thanks for your patience, I couldnt find the right buttons in the mobile github app ;-). Improving docs is always very welcome snd helps the project and most of all future users! all the best!

2023-01-22 12:50 UTC, merged