Documentation Updates
joalla/discogs_client pull request #69
Opened 2021-12-12 00:53 UTC by prcutler

Related to #67 

I started by making some small grammar and typo fixes on a couple of pages.  I also added a note not to share or commit your token.

I then renamed the `fetching_data.md` page that uses the REPL to differentiate it from the page I wrote that also shows some of the returns when using a print statement.

Before I write up how to fetch your data in your personal collection, please share any feedback.  I'm undecided if I should split it into two pages or not.  If it doesn't meet your standards, please feel free to let me know and I will re-write and edit it.  You won't hurt my feelings. :)

Thanks again for this great library and especially all the help learning it.

2021-12-12 10:39 UTC, JOJ0 commented
Unfortuantely it's not possible to let the documentation render online on readthedocs.io to see what it would finally look like. In any case make yourself comfortable with the index files written in restructured text format: https://github.com/joalla/discogs_client/blob/master/docs/source/index.rst

We use Sphinx to generated the final doc. What you _could_ do to see the rendered final docs is install Sphinx locally and then just open the generated html files locally. You find the requirments for that in sphinx_requirements.txt. Once you installed try to generate the docs using `make html` inside the docs root dir `docs/` Get back to me whether that works I am not sure if I got this right from the top of my head.

2021-12-12 10:49 UTC, prcutler commented
It's been a few years since I used rST and Sphinx, but I can send a PR that includes the rST files for Readthedocs.  Sorry for the confusion, the [comment here in #64](https://github.com/joalla/discogs_client/discussions/64#discussioncomment-1555616) made me think it would work in markdown.

I'll incorporate your comments above and revise it and send a PR in rST in the next day or two.

Thanks!

2021-12-12 10:56 UTC, JOJ0 commented
No, it's fine in markdown. The documentation page your wrote is perfectly fine in markdown and we want it that way! We use a markdown plugin for Sphinx that handles that.
It is the index files only that need to be written in .rst. But it's rather self-explanatory. Adding a news file is as easy as just putting the filename into a new line :-)

2021-12-12 10:58 UTC, JOJ0 commented
Have a look here again, it's all md files that are stated inside this .rst index file ;-) https://github.com/joalla/discogs_client/blob/master/docs/source/index.rst

2021-12-12 12:36 UTC, prcutler commented
That makes more sense.  I'll get working on the changes and the index file.  Thanks for clarifying.

2021-12-13 19:44 UTC, prcutler commented on docs/source/fetching_data_repl.md
>  an existing [Client object](quickstart.md) already.
I agree - I know I did code examples vs. the REPL, but I think having both is good for how people prefer to learn a new API.  I'll take a look and I'm updating the PR with the typos - thanks for the extra set of eyes.  

In contribution, I made a link to the Ideas section of Discussions, that should help as well.

2021-12-13 19:52 UTC, prcutler commented on docs/source/fetching_data_repl.md
>  an existing [Client object](quickstart.md) already.
Here's my suggestion and PR:
```
Note that the examples in this chapter are shown using a Python REPL and require an existing [Client object](quickstart.md) already. Using the Python REPL can be an easy way to test and review data and information available using the Discogs API.
```

2021-12-13 20:07 UTC, prcutler commented
Sorry about all the commits, I'm still newish to VS Code and was trying to use that with PRs.  I still need to write the section on querying a user's specific collection.  It might be a few days until I get that one done.

Thanks again for all the feedback.

2021-12-14 07:07 UTC, JOJ0 commented
> I realized I committed to the main branch in my repository, so the update is listed as the Merge Pull Request above.

That's fine with me, no worries, but a quick note on git usage because I think you might appreciate learning something new every day :-)

Not sure how you did this "merge request", maybe vscode did that for you. But in any case, you don't need to send merge or pull requests to yourself. You could have just merged your two branches using a few git commands and this PR would have been magically updated with the correct commits:

```
git checkout master
git merge docs-update-dec21
git push
```

Then continue just working in your master branch. Since you opened the PR from your master branch to the joalla master branch, this is perfectly fine.

2021-12-14 07:19 UTC, JOJ0 commented
I am not sure if you managed to build the docs and see what they finally look like and whether everything is displayed in the inventory and indexes properly. These are the steps necessary I guess (Also something that's probably missing in our docs, but rather in the contribution section I think):
```
# launch your development venv and install sphinx requirements into it:
pip install -r sphinx_requirements.txt
git checkout your_feature_branch  # or just master in your case
python setup.py develop  # the package needs to be installed, otherwise Sphinx won't find it
cd docs
make html  # shouldn't throw too much "red" lines
# Open the built docs in a browser, on Linux that probably would be something like that:
xdg-open build/html/index.html
```
It helps me personally to often have a look at the final generated docs to really see what it looks like and spotting final errors.

2021-12-14 07:26 UTC, JOJ0 commented
Oh there is quite some "red" during the make command. Please ignore lines like this:
```
docstring of discogs_client.models.ListItem.id:10: WARNING: Unexpected indentation.
docstring of discogs_client.models.ListItem.comment:10: WARNING: Unexpected indentation.
docstring of discogs_client.models.ListItem.display_title:10: WARNING: Unexpected indentation.
docstring of discogs_client.models.ListItem.type:10: WARNING: Unexpected indentation.
docstring of discogs_client.models.ListItem.image_url:10: WARNING: Unexpected indentation.
```

but consider any other red lines / get back to me with questions. Thanks!

2021-12-14 07:28 UTC, JOJ0 commented
please rename the file fetching_data_code.md to just fetching_data.md

2021-12-14 07:35 UTC, JOJ0 commented on docs/source/fetching_data_repl.md
>  an existing [Client object](quickstart.md) already.
Using the Python REPL can be an easy way to test and review the information discogs_client is retrieving from the Discogs API.

You might want to rephrase that again, but would I'd like to get across the net ist that this is the way to "see what the data looks like when presented through discogs_client"

2021-12-14 07:38 UTC, JOJ0 commented
> Sorry about all the commits, I'm still newish to VS Code and was trying to use that with PRs. I still need to write the section on querying a user's specific collection. It might be a few days until I get that one done.
> 
> Thanks again for all the feedback.

No worries, as mentioned somewhere else already :-) I use vscode as well but can't get my head around clicking so much things when I could just use plain old git commands. I think understanding git on the cli first is key to be comfortable and understand what guis are doing. But that might be just my opinion. Work away, you'll understand what it does at some point! :-)

2021-12-14 11:25 UTC, prcutler commented
Thanks for the feedback - I'm going back to using the CLI again!  It's been almost 10 years since I've been active in an open source project and I'm a bit rusty.  Appreciate the tips!

I'll get these fixes done and build it locally too.

2021-12-15 02:20 UTC, prcutler commented
Just tried to build the docs and it fails.  Any hints?  Sorry to be so much trouble.

```
discogs_client/docs on  master [?] via 🐍 v3.10.0 (.venv) 
❯ make html
Traceback (most recent call last):
  File "/Users/prcutler/workspace/discogs_client/.venv/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/Users/prcutler/workspace/discogs_client/.venv/lib/python3.10/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/Users/prcutler/workspace/discogs_client/.venv/lib/python3.10/site-packages/sphinx/application.py", line 32, in <module>
    from sphinx.config import Config
  File "/Users/prcutler/workspace/discogs_client/.venv/lib/python3.10/site-packages/sphinx/config.py", line 23, in <module>
    from sphinx.util import logging
  File "/Users/prcutler/workspace/discogs_client/.venv/lib/python3.10/site-packages/sphinx/util/__init__.py", line 35, in <module>
    from sphinx.util import smartypants  # noqa
  File "/Users/prcutler/workspace/discogs_client/.venv/lib/python3.10/site-packages/sphinx/util/smartypants.py", line 33, in <module>
    from sphinx.util.docutils import __version_info__ as docutils_version
  File "/Users/prcutler/workspace/discogs_client/.venv/lib/python3.10/site-packages/sphinx/util/docutils.py", line 31, in <module>
    from sphinx.util.typing import RoleFunction
  File "/Users/prcutler/workspace/discogs_client/.venv/lib/python3.10/site-packages/sphinx/util/typing.py", line 34, in <module>
    from types import Union as types_Union
ImportError: cannot import name 'Union' from 'types' (/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/types.py)
make: *** [html] Error 1

discogs_client/docs on  master [?] via 🐍 v3.10.0 (.venv) 
❯ 
```

2021-12-15 06:33 UTC, JOJ0 commented
> Just tried to build the docs and it fails. Any hints? Sorry to be so much trouble.

No trouble at all! We appreciate all your efforts to improve docs and find possible problems like this one for future contributors! :-)

>     from types import Union as types_Union
> ImportError: cannot import name 'Union' from 'types' (/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/types.py)
> make: *** [html] Error 1
> 
> discogs_client/docs on  master [?] via 🐍 v3.10.0 (.venv) 

Seems you are using Python 3.10. Any chance you could try it with Python 3.9? Will try 3.10. if I find the time though. Maybe Sph8inx doesn't like that (yet).

Also: Did all your pip install commands go through flawlessly? Send a pip list please.

2021-12-15 10:26 UTC, prcutler commented
It was Python 3.10 (of course!)

I know I'm saying it alot, but thanks.

2021-12-25 19:20 UTC, prcutler commented
I may have been distracted building my project now that I know the API. :) I think I have all changes you asked for - I was able to get it to build. I fixed a couple of the errors it showed me and that I found.  I also reworked that opening paragraph for the REPL chapter again, so take a look and let me know your thoughts.

I still need to write the section on querying a user's collection data, I haven't forgot.  Also, if there is any documentation that needs to be written or edited, feel free to mention me or assign issues to me, I'm happy to help.

2022-01-14 06:45 UTC, JOJ0 commented
Hi @prcutler, sorry for the rather long silence here. I think I was facing exactly that kind of distraction you are describing :-)

Thank you so much for your your efforts. I just built the docs and are now reviewing the final html. I am sure we will get this release-ready soon. Also thank you very much for the offer for future docs. I am sure there is plenty of opportunity. Most of the time as you probably are aware of already, things that need documenting come out of github discussions or issues. Feel free to suggest in a discussion that there is a need by mentioning me and I'll try to do the same by pointing you there! Thanks again! That's awesome news!

2022-01-14 07:41 UTC, JOJ0 requested changes
Alright, some change requests. I do love how the new chapters list now looks like. I think it's structured well. Also the chapter you wrote starting with exploring with dir() and stuff will be very helpful to new users and will certainly help us maintainers as well. We'd just have to point to this well written docs when stuff is asked in discussions. Love it! Thanks!

![Screen Shot 2022-01-14 at 08 40 42](https://user-images.githubusercontent.com/2733783/149469805-83a6b208-daa0-4c49-946d-7474f2608bce.png)

2022-01-14 07:41 UTC, JOJ0 commented on docs/source/fetching_data.md
> +###Artists
I think there is a space missing, it doesn't render correctly. Also I suggest you always use full code blocks instead of "inline single tick" code markup because the readthedocs template renders these very different (red font) and it's easier to read if everything has the boxes with grey background. Have a look on the final render, that's easier than explaining with words:


![Screen Shot 2022-01-14 at 07 54 08](https://user-images.githubusercontent.com/2733783/149465204-a6ce8906-c0f6-41d2-bbac-1b05ecd70a96.png)

2022-01-14 07:41 UTC, JOJ0 commented on docs/source/fetching_data.md
> +Data returns JSON including the URL to the page for the given release:
Technically it's a dict. Requests library already translated it from json string to a python dict.

2022-01-14 07:41 UTC, JOJ0 commented on docs/source/fetching_data.md
> +This returns a list as some releases have multiple artists:
And then rephrase this to:

Artists are always returned as a list as some releases have multiple artists:

2022-01-14 07:41 UTC, JOJ0 commented on docs/source/fetching_data.md
> -```
A chapter about labels would be nice since this was asked often in issues/discussions: How to get the catalog number. It's hidden in the labels dict data. Similar story as .artists and .format:

- .labels is a list
- catalog numbers are hidden inside each single label's data dict (each label that released often has it's own catalog number). Eg: `.labels[0].data['catno']`

(and yes it whould be a nice addition to the library if the catno could be accessed like .labels[0].catno` - I want to make a pull for this for ages already ;-) Not your concern right, just reminding myself :-))

2022-01-14 17:34 UTC, prcutler commented
Thanks for the feedback.  I'll get the changes done this weekend.  And I still owe more docs, other projects have distracted me.  :)

2022-01-19 12:24 UTC, prcutler commented
Thank you!  I'll get the fixes done in the next few days.

2022-01-26 06:59 UTC, JOJ0 commented
> Thank you! I'll get the fixes done in the next few days. I may open a new issue for the new chapter.

Hi, yes please leave out the Collection chapter for now and let's focus on finishing the pending changes in this PR first.
Also please don't include the chapter about labels I suggested in this PR (if you haven't started yet) because it was my suggestion and is something new again. I might even write this chapter myself or wait until a feature around this is implemented and write the docs afterwards.
Thanks for your efforts!

2022-01-26 12:29 UTC, prcutler commented
Ok - I'll get this done tomorrow, I'm tied up today.

Thanks!

2022-01-30 15:58 UTC, JOJ0 requested changes

2022-01-30 15:58 UTC, JOJ0 commented on docs/source/writing_docs.md
> +The second step is to clone the ```python3-discogs-client``` library to your computer.  From the ```python3-discogs-client``` fork you just created, press the ```Code``` button and copy the ```git```
....press the Code button, copy the git URL and clone it in your code editor of choice or just use the terminal:

 ```
 git clone <git url>
 ```

2022-01-30 15:58 UTC, JOJ0 commented on docs/source/writing_docs.md
> +
```
git checkout -b my_docs_additions_branch
```

2022-01-30 15:58 UTC, JOJ0 commented on docs/source/contribution.md
> +You can help keep the documentation current by editing or adding new pages to the documentation.  Please see the [Writing Documentation page](writing_docs.md) for more information on how to clone the
I'm still thinking about whether or not the docs chapter should be filed under the "contribution" chapter, but on the other hand, I like having such a nice separate major chapter for docs only. Also I like that you explain some git basics there since I think we can assume that people that contribute actual code to a library probably know the git basics already but newish users to python hacking and using a library might not. Giving them a nice starting point for improving unclear things in the docs is a good thing. Well done Peter! Let's get this merged! Just a few changes requested.

2022-01-30 16:27 UTC, prcutler commented
I've got a 3.9 venv setup, but I"m getting an error trying to build the docs:

```
make html
Running Sphinx v4.4.0
WARNING: sphinx_rtd_theme (< 0.3.0) found. It will not be available since Sphinx-6.0
```

The changes are in the updated PR, I just haven't verified them.

2022-01-31 19:08 UTC, JOJ0 commented on docs/source/writing_docs.md
> +  ```
and here too.

2022-02-01 04:59 UTC, JOJ0 approved these changes

2022-02-01 06:48 UTC, merged

2022-02-01 06:48 UTC, JOJ0 commented
Thanks again @prcutler for these great additions and refinements to our docs!